apiVersion: v1
kind: Service
metadata:
  name: gallery-service
  namespace: image-gallery
spec:
  selector:
    app: gallery
  ports:
    - port: 80          # inside cluster
      targetPort: 5000  # Flask in container
  type: NodePort        # easy to access from laptop
