apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
  namespace: image-gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
        - name: gallery
          image: upload-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
